
__default__:
# default parameter for all rules
  queue: "{{cookiecutter.default_queue}}" # required
  nodes: 1


# The following rules in atlas need need more time/memory.
# If you need to submitt them to different queues you can vonfigure this as outlined.

# run_megahit:
#   queue: bigmem
# run_spades:
#   queue: bigmem

#gtdb-tk classify uses 'large_mem' and log time
# classify:
#   queue: bigmem-long

# run_checkm_lineage_wf:
#   queue: long

# run_all_checkm_lineage_wf:
#   queue: long

#You can overwrite values for specific rules

  #account: ""
  #time:  # h
  #mem:  # GB
  #threads:
