restart-times: 0
cluster-config: "$((INSTALDIR))/cluster_spec.yaml" #abs path
cluster: "scheduler.py" #
cluster-status: "{{cookiecutter.cluster_system}}_status.py" #
max-jobs-per-second: 10
max-status-checks-per-second: 10
cores: 99 # how many jobs you want to submit to your cluster queue
local-cores: 1
rerun-incomplete: true  # recomended for cluster submissions
keep-going: true
