restart-times: 0
cluster: "{{cookiecutter.abs_path}}"/"{{cookiecutter.profile_name}}"/slurm_scheduler.py" #
cluster-status: "{{cookiecutter.abs_path}}"/"{{cookiecutter.profile_name}}"/slurm_status.py" #
cluster-config: "{{cookiecutter.abs_path}}"/"{{cookiecutter.profile_name}}"/cluster_spec.yaml" #abs path
max-jobs-per-second: 1
max-status-checks-per-second: 10
#cores: 99 # how many jobs you want to submit to your cluster queue
local-cores: 1
rerun-incomplete: true
conda-prefix: "{{cookiecutter.abs_path}}"/conda_envs" # path to folder where to save conda envs
keep-going: true
